name: Build and Test

on:
  push:
    branches: [ master, main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main, develop ]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Verify binary
        run: |
          ls -lh bin/pinpoint-linux-amd64
          file bin/pinpoint-linux-amd64

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...

  release:
    name: Create Release
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build multi-platform binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/pinpoint-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/pinpoint-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o dist/pinpoint-darwin-amd64 .
          GOOS=windows GOARCH=amd64 go build -o dist/pinpoint-windows-amd64.exe .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: false
          prerelease: false
